version: "3.8"

services:
  backend:
    build:
      context: ./gerador-ia-back
      dockerfile: Dockerfile
    container_name: gerador-backend
    env_file:
      - ./gerador-ia-back/.env
    volumes:
      - ./gerador-ia-back:/app
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./gerador-ia-front
      dockerfile: Dockerfile
    container_name: gerador-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./gerador-ia-front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
